### ISSUE TITLE
Checksum Fail

### ISSUE THREAD

**Issue by mauinate** [wvmarle/Arduino_DS1603L#2]
I know this is old!  I'm trying to implement this sensor, btw I am new at all of this so go easy :)

I am getting a valid reading maybe 1 out of 7-8 readings.  The rest have a failed checksum.  I've tried two different sensors, and 2 different arduinos.  No luck, same results.  Any ideas?  Thanks!

**Comment by wvmarle** [comment]
My best guess is a problem with the Serial communications - poor wire connections or too long wires.

**Comment by mauinate** [comment]
Thank you, I'll check everything and re-solder!
